spring.application.name=backend

##spring.datasource.url=jdbc:mysql://localhost:3306/google
##spring.datasource.username=root
##spring.datasource.password=


spring.datasource.url=jdbc:mysql://zephyr.proxy.rlwy.net:58496/railway
spring.datasource.username=root
spring.datasource.password=NinXJrwSqDoWXOKacYbdDUGVKtCowlpH

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081

jwt.secret=taxiappsupersecretkeytaxiappsupersecretkey
jwt.expiration=86400000